import Foundation

/// Build tool that reads YAML files from a Defaults directory and generates
/// a Swift source file with their contents embedded as string literals.
@main
struct EmbedDefaultsTool {
    static func main() throws {
        guard CommandLine.arguments.count == 3 else {
            fputs("Usage: EmbedDefaultsTool <defaults-dir> <output-file>\n", stderr)
            exit(1)
        }

        let defaultsDir = CommandLine.arguments[1]
        let outputFile = CommandLine.arguments[2]
        let fm = FileManager.default

        var entries: [(path: String, content: String)] = []
        var directories: Set<String> = []

        if fm.fileExists(atPath: defaultsDir) {
            try collectEntries(
                in: defaultsDir,
                relativeTo: defaultsDir,
                entries: &entries,
                directories: &directories
            )
        }

        let swift = generateSwift(entries: entries, directories: directories.sorted())

        let outputDir = (outputFile as NSString).deletingLastPathComponent
        try fm.createDirectory(atPath: outputDir, withIntermediateDirectories: true)
        try swift.write(toFile: outputFile, atomically: true, encoding: .utf8)
    }

    static func collectEntries(
        in dir: String,
        relativeTo base: String,
        entries: inout [(path: String, content: String)],
        directories: inout Set<String>
    ) throws {
        let fm = FileManager.default
        let items = try fm.contentsOfDirectory(atPath: dir).sorted()

        for item in items where !item.hasPrefix(".") {
            let fullPath = (dir as NSString).appendingPathComponent(item)
            let relativePath = String(fullPath.dropFirst(base.count + 1))

            var isDir: ObjCBool = false
            fm.fileExists(atPath: fullPath, isDirectory: &isDir)

            if isDir.boolValue {
                directories.insert(relativePath)
                try collectEntries(
                    in: fullPath,
                    relativeTo: base,
                    entries: &entries,
                    directories: &directories
                )
            } else {
                let content = try String(contentsOfFile: fullPath, encoding: .utf8)
                entries.append((path: relativePath, content: content))
            }
        }
    }

    static func generateSwift(
        entries: [(path: String, content: String)],
        directories: [String]
    ) -> String {
        var lines: [String] = []
        lines.append("// Auto-generated by EmbedDefaultsTool — do not edit.")
        lines.append("")
        lines.append("enum EmbeddedDefaults {")
        lines.append("    struct Entry: Sendable {")
        lines.append("        let path: String")
        lines.append("        let content: String")
        lines.append("    }")
        lines.append("")
        lines.append("    static let files: [Entry] = [")
        for entry in entries {
            let escaped = entry.content
                .replacingOccurrences(of: "\\", with: "\\\\")
                .replacingOccurrences(of: "\"", with: "\\\"")
                .split(separator: "\n", omittingEmptySubsequences: false)
                .joined(separator: "\\n")
            lines.append("        Entry(path: \"\(entry.path)\", content: \"\(escaped)\"),")
        }
        lines.append("    ]")
        lines.append("")
        lines.append("    static let directories: [String] = [")
        for dir in directories {
            lines.append("        \"\(dir)\",")
        }
        lines.append("    ]")
        lines.append("}")
        lines.append("")
        return lines.joined(separator: "\n")
    }
}
